version: '3.3'
services:
  redis_db_service:
    image: redis:alpine
    container_name: cache
    ports:
      - 6379:6379

  webapi_dot_net:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    ports:
      - 8093:8093
    volumes:
      - ./src:/app
    working_dir: /app
    command: bash -c "dotnet run"
    depends_on: 
      - redis_db_service
    links: 
      - redis_db_service:redis_db_service